Change the `--all` flag to cooperate with the new `--extension` flag.
bcoe/c8 pull request #357
Opened 2022-02-09 21:13 UTC by brev

Change the `--all` flag to cooperate with the new `--extension` flag.

Instead of a few hard-coded extensions, `--all` will now respect any
custom extensions.

Backwards compatible if `--extension` flag is not used.

New test added, snapshots updated, everything is passing.

As an example: I'm using esmodule loaders to have Node.js load `.svelte` files
(see: [esm-loader-svelte](https://github.com/brev/esm-loader-svelte)). This
works great with the `--extension` flag, but `--all` was missing this new
extension. With this changeset, everything now works great.

##### Checklist

- [x] `npm test`, tests passing
- [x] `npm run test:snap` (to update the snapshot)
- [x] tests and/or benchmarks are included

2022-02-26 19:00 UTC, bcoe requested changes
Work looks great, just one suggestion.

Also, you just need to:

```
nvm use 10
npm run test:snap
```

To capture snapshots for Node 10

2022-03-01 00:54 UTC, brev commented on test/integration.js.snap
> +  index.js                             |       0 |        0 |       0 |       0 | 1
I think they are already set to `clean=false`, did you mean change them to `clean=true`?  thanks.

2022-03-01 01:12 UTC, brev commented
> To capture snapshots for Node 10

Done! thanks. :)

2022-03-23 18:21 UTC, bcoe commented
@brev apologies for the slow review. Could I bother you to update your snapshots using `--clean=true` so that your fixtures don't include output from the prior test.

2022-03-29 01:42 UTC, brev commented
> @brev apologies for the slow review. Could I bother you to update your snapshots using `--clean=true` so that your fixtures don't include output from the prior test.

Hello @bcoe, I've updated the snapshots with your `--clean=true` change. Thank you!

2022-03-30 18:46 UTC, darkangel081195 commented
Can i please know when will the PR be merged.

Thanks in advance.

2022-04-12 09:13 UTC, NagariaHussain commented
Could this be reviewed on priority @bcoe ? Causing issue while setting up vitest test coverage with vue and js files. Is there a hack we can use in the mean time?

2022-04-19 12:44 UTC, Lyokolux commented
> Could this be reviewed on priority @bcoe ? Causing issue while setting up vitest test coverage with vue and js files. Is there a hack we can use in the mean time?

I'm watching this PR carefully to see what version it will be merged into

2022-04-20 13:09 UTC, bcoe commented on test/integration.js.snap
> +  index.js                             |       0 |        0 |       0 |       0 | 1
Yes, `clean=true`, if you don't mind :+1: then we can have less noisy test output.

2022-04-20 13:09 UTC, bcoe commented
@Lyokolux PR looks good to me, just need to cleanup the tests a bit to not include extra files.

2022-04-20 21:12 UTC, brev commented on test/integration.js.snap
> +  index.js                             |       0 |        0 |       0 |       0 | 1
Hi @bcoe, I believe `clean=true` is now set, as of my last commit.  Please confirm?  Thanks!

2022-04-22 06:47 UTC, Asim-Tahir commented
@NagariaHussain
> Is there a hack we can use in the mean time?

[Referencing this StackOverflow answer](https://stackoverflow.com/questions/43411864/how-to-install-package-from-github-repo-in-yarn)

## For Yarn 1 `UNTESTED`
```
yarn add git+https://github.com/brev/c8.git#all-flag-includes-extensions -D
```

## For Yarn 2+ `✅TESTED`
```
yarn add c8@https://github.com/brev/c8#head=all-flag-includes-extensions -D
```

## For NPM `UNTESTED`
```
npm i brev/c8#all-flag-includes-extensions -D
```

2022-04-26 15:05 UTC, volarname commented
+1 for merge

2022-05-16 00:41 UTC, bcoe approved these changes

2022-05-16 00:50 UTC, merged

2022-05-16 00:51 UTC, bcoe commented
@brev thank you for the contribution, sorry that it took so long to merge.

2022-05-16 03:02 UTC, brev commented
@bcoe Thank you for the amazing project, and the hard work and sacrifice!